{
 "title": "MLOps_Dashboard",
 "time": { "from": "2023-02-28T19:00:00.000Z", "to": "2023-03-31T18:59:59.000Z" },
 "panels": [
  {
   "title": "Prediction drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM ny_taxi_trip_prediction_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Quantile metric (fare amount)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", quantile_metric FROM ny_taxi_trip_prediction_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Correlation (`total_amount` vs`trip_distance`)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", correlation_metric FROM ny_taxi_trip_prediction_metrics LIMIT 50 "
    }
   ]
  }
 ]
}